### ISSUE TITLE
Uppmax netflow installation information

### ISSUE THREAD

**Issue by viklund** [NBISweden/wgs-structvar#2]
To make nextflow installable in the module system on Uppmax I need to contact the person who installed it on uppmax so I can figure out how to fix it.

**Comment by pallolason** [comment]
Doug Scofield installed. Then later, the module was removed without any notice, email reply to installation request follows. I believe they are still trying to get it installed, at least on Irma

´´´
Hej Pall,

Nextflow är installad som modul Nextflow/0.17.3.

Det finns inte 'global' configfil för denna modulen, men NXF_HOME är inställd
till modulen.

Mvh, Doug
´´´
