### ISSUE TITLE
CNVnator problem

### ISSUE THREAD

**Issue by viklund** [NBISweden/wgs-structvar#42]
Jag lyckas inte få CNVnator att generera någon output. Root-filen skapas,
men det verkar som att det är något som jag saknar, jag får lite varningar
från programmet. Det här är mitt nuvarande run-script (jag provade att
kopiera referensfilerna och byta namn på dem ifall det var det som var
felet, därav två olika REF_PATH).

``` bash
#!/bin/bash
module load bioinfo-tools
module load CNVnator

ROOTFILE=out.root
CHROM=chr20
#BAMFILEºmfile

BAMFILE=/proj/a2009002/webexport/opendata/HiSeqX_CEPH/CEP-1-7/03-BAM/CEP-1-7.clean.dedup.recal.bam
#REF_PATH=/sw/data/uppnex/reference/Homo_sapiens/GRCh37/chromosomes
REF_PATH=./chr

cnvnator -root $ROOTFILE -chrom $CHROM -unique -tree -d $REF_PATH $BAMFILE
cnvnator -root $ROOTFILE -chrom $CHROM -his 100 -d $REF_PATH
cnvnator -root $ROOTFILE -chrom $CHROM -stat 100 -d $REF_PATH
cnvnator -root $ROOTFILE -chrom $CHROM -partition 100 -d $REF_PATH
cnvnator -root $ROOTFILE -chrom $CHROM -call 100 -d $REF_PATH > outfile.call
```

Och när jag kör det (tar ungefär 10sekunder på login noden), får jag
följande output:

```
Parsing stdin ...
No chromosome/contig description given.
No reference genome specified. Aborting parsing.
Writing histograms ...
Total of 0 reads were placed.
Allocating memory ...
Can't determine length for 'chr20'.
No reference genome specified.
Done.
Calculating histograms with bin size of 100 for 'chr20' ...
Making statistics for chr20 ...
Can't find RD histogram for 'chr20'.
Can't find unique RD histogram for 'chr20'.
Average RD per bin (1-22) is 0 +- 0 (before GC correction)
Average RD per bin (X,Y)  is 0 +- 0 (before GC correction)
Correcting counts by GC-content for 'chr20' ...
Making statistics for chr20 after GC correction ...
Can't find histogram for 'chr20'.
Average RD per bin (1-22) is 0 +- 0 (after GC correction)
Average RD per bin (X,Y)  is 0 +- 0 (after GC correction)
Can't find all histograms for 'chr20'.
Can't find all histograms for 'chr20'.
```

**Comment by andkaha** [comment]
The chromosome might be called "20" rather than "chr20".

**Comment by viklund** [comment]
Good suggestion, but sadly, no, that change didn't work (for me).

**Comment by pallolason** [comment]
$ cd data
$ mkdir fasta
$ cp /sw/data/uppnex/reference/Homo_sapiens/GRCh37/chromosomes/Homo_sapiens.GRCh37.57.dna.chromosome.20.fa fasta/20.fa
$ cnvnator -root CEP-1-7.clean.dedup.recal.chr20.root -chrom 20 -tree CEP-1-7.clean.dedup.recal.chr20.bam
$ cnvnator -root CEP-1-7.clean.dedup.recal.chr20.root -chrom 20 -his 500 -d fasta/
$ cnvnator -root CEP-1-7.clean.dedup.recal.chr20.root -chrom 20 -stat 500
$ cnvnator -root CEP-1-7.clean.dedup.recal.chr20.root -chrom 20 -partition 500
$ cnvnator -root CEP-1-7.clean.dedup.recal.chr20.root -chrom 20 -call 500 | cnvnator2VCF.pl -

**Comment by pallolason** [comment]
tah dah...

**Comment by viklund** [comment]
The problem was that I called the bamfile `bamfile` and not `bamfile.bam`
