### ISSUE TITLE
Is vt needed for snpEFF?

### ISSUE THREAD

**Issue by viklund** [NBISweden/wgs-structvar#43]
The snpEff input file is currently preprocessed through `vt` in the following way:

```
    sed 's/ID=AD,Number=./ID=AD,Number=R/' "\$vcf" \
        | vt decompose -s - \
        | vt normalize -r $params.ref_fasta - \
        | java -Xmx7G -jar "\$SNPEFFJAR" -formatEff -classic GRCh37.75 \
        > "\$vcf.snpeff"
```

If `vt` is not strictly needed we can run snpEff directly on the `.bed` files. `vt` is not used for VEP.

**Comment by pallolason** [comment]
I doubt that effect change will be huge with normalization - its usually just a single base that the coords shift, but preferrably run vt in both cases, VEP and snpeff
