### ISSUE TITLE
vcf headers

### ISSUE THREAD

**Issue by viklund** [NBISweden/wgs-structvar#45]
Currently I'm just `cat`ing the vcf files together. I get header lines in the middle of the files and `vep` at least seem to be fine with that. Is there a better way?

I tried `vcf-concat` from vcftools but it complained since the `manta` output had 10 columns instead of 8 for `fermikit`. The extra columns were "FORMAT" and "CEP-1-7" (example information in the extra columns: `GT:FT:GQ:PL:PR:SR       0/1:PASS:345:395,0,428:15,6:12,12`). And if I cut them away I only get the header for the first `vcf` file. I could of course just merge the headers and cut away column 9 and 10 and remove doubly defined header lines, should be quite simple.

**Comment by andkaha** [comment]
I'm using `bcftools concat -Oz -a one.vcf.gz another.vcf.gz >new.vcf.gz` For the SweFreq project with the most recent version of `bcftools` (with `--version` it says "`1.3.1-113-g395c060`").

**Comment by pallolason** [comment]
bcftools also complains about different #cols  (I much prefer bcftools to vcftools in general)

**Comment by pallolason** [comment]
right now, Im thinking we cut the individual genotype from manta (FORMAT + sample gt) columns - we are calling individual samples anyway.
not hacky at all...
    $ vcf-concat fermikit.vcf <((cat manta.vcf | grep "^##"; cat manta.vcf | grep -v "^##" | cut -f 1-8))

**Comment by andkaha** [comment]
Pall, that shell code will probably work, but it doubles the disk access by parsing the file twice. It's better to do it in an `awk` script:

```
$ vcf-concat fermikit.vcf <( awk 'BEGIN {OFS="\t"} /^##/ {print; next} {print $1,$2,$3,$4,$5,$6,$7,$8}' manta.vcf )
```

**Comment by pallolason** [comment]
aye aye, captain I/O, well spotted  ;)
