### ISSUE TITLE
Slurm memory overflow on variant effect prediction

### ISSUE THREAD

**Issue by dnil** [NBISweden/wgs-structvar#63]
Running a regular wgs bam with --steps manta,vep

```nextflow run main.nf --project b2014152 --bam /proj/b2014152/private/delivery/P2109/P2109_150/03-BAM/P2109_150.clean.dedup.recal.bam --steps manta,vep```

Works up until:
```[1c/4f4270] Submitted process > variant_effect_predictor (4df25178-37e0-40ea-a02c-114782119240 - manta_masked.vcf)```

Then got an email back with:
```UPPMAX: Memory overflow error on host m116 for job 9775456 (/nf-variant_effect_predictor_(4df25178-37e0-40ea-a)```

At about 8 Gb; 

the offending line happens to be
```
  gzip: /sw/data/uppnex/vep/84/homo_sapiens_merged/84_GRCh37/16/11000001-12000000.gz: Cannot allocate memory
  .command.sh: line 15:  9836 Killed                  variant_effect_predictor.pl -i "$INFILE" --format "$FORMAT" -cache --dir "$VEP_CACHE" -o "$OUTFILE" --vcf --merged --regulatory --force_overwrite --sift b --polyphen b --symbol --numbers --biotype --total_length --canonical --ccds --fields Consequence,Codons,Amino_acids,Gene,SYMBOL,Feature,EXON,PolyPhen,SIFT,Protein_position,BIOTYPE --assembly "$ASSEMBLY" --offline
```
Did it work ok for you? Allocate more mem / cores?

**Comment by viklund** [comment]
Tested a bit. Running vep on 4 cores instead of 1 (with `--forks 4` as parameter) solves this.

**Comment by glormph** [comment]
#71 fixes this
