### ISSUE TITLE
Readme.md should contain all information needed for running the workflow

### ISSUE THREAD

**Issue by viklund** [NBISweden/wgs-structvar#66]
- [ ] How to get support if there are any problems.
- [x] Documentation on parameters.
- [x] How to change modules used in the module system used if that is required.
- [x] How a runfile is specified.
- [x] How to run the entire nextflow pipeline as a SLURM 
- [x] Where the log file for the run is stored and possibly information about it if it's unclear.

**Comment by glormph** [comment]
How will support be delivered? I wrote a placeholder in the README.

-- edit: We will ask relevant stakeholder where support will be coming from.
