### ISSUE TITLE
The help message should be clear

### ISSUE THREAD

**Issue by viklund** [NBISweden/wgs-structvar#67]
- [x] All parameters documented (briefly)
- [x] _Maybe_ support short help and long help message.
- [x] A pointer to the documentation on github.
- [x] Information about where the log file is stored.

**Comment by glormph** [comment]
Point 1 - All cmd line parameters seem already mentioned in the help text, but maybe I am missing something here?

**Comment by viklund** [comment]
I don't think you are missing anything. I just wasn't sure if they were.
