### ISSUE TITLE
What human reference?

### ISSUE THREAD

**Issue by viklund** [NBISweden/wgs-structvar#9]
The makefile refers to 2 different human reference locations:

```
REF_FASTA:=/sw/data/uppnex/ToolBox/ReferenceAssemblies/hg38make/bundle/2.8/b37/human_g1k_v37.fasta
GENOME_REF_FILE=/sw/data/uppnex/reference/Homo_sapiens/g1k_v37/concat/human_g1k_v37.fasta
```

`REF_FASTA` is used by manta the other by fermikit. It is only by the `REF_FASTA` the extra indexes (for bam and so forth) already exists, so I have used that path for all of the programs.

**Comment by pallolason** [comment]
yep, lets go for the REF_FASTA target
